In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import word_tokenize
import nltk

In [2]:
df = pd.read_csv(r'C:\Users\nickm\Documents\DailyComments.csv')

In [3]:
df.head()

Day of Week                                        comments
0      Monday                             Hello, how are you?
1     Tuesday                            Today is a good day!
2   Wednesday  It's my birthday so it's a really special day!
3    Thursday       Today is neither a good day or a bad day!
4      Friday                           I'm having a bad day.

In [4]:
df

Day of Week                                        comments
0      Monday                             Hello, how are you?
1     Tuesday                            Today is a good day!
2   Wednesday  It's my birthday so it's a really special day!
3    Thursday       Today is neither a good day or a bad day!
4      Friday                           I'm having a bad day.
5    Saturday       There' s nothing special happening today.
6      Sunday                      Today is a SUPER good day!

In [5]:
#Converting text to lower case
df['comments'] = df['comments'].str.lower()

In [6]:
df['comments']

0                               hello, how are you?
1                              today is a good day!
2    it's my birthday so it's a really special day!
3         today is neither a good day or a bad day!
4                             i'm having a bad day.
5         there' s nothing special happening today.
6                        today is a super good day!
Name: comments, dtype: object

In [7]:
import unicodedata
import sys

#creating punctuation dictionary
punctuation = dict.fromkeys(i for i in range(sys.maxunicode)
    if unicodedata.category(chr(i)).startswith('P'))

In [8]:
#removing punctuation for each string in the data frame
df['comments']=[string.translate(punctuation) for string in df['comments']]

In [9]:
df['comments']

0                              hello how are you
1                            today is a good day
2    its my birthday so its a really special day
3       today is neither a good day or a bad day
4                            im having a bad day
5        there s nothing special happening today
6                      today is a super good day
Name: comments, dtype: object

In [22]:
#corpus = df['comments']
corpus = df.comments.apply(str)

In [23]:
corpus

0                              hello how are you
1                            today is a good day
2    its my birthday so its a really special day
3       today is neither a good day or a bad day
4                            im having a bad day
5        there s nothing special happening today
6                      today is a super good day
Name: comments, dtype: object

In [24]:
count= CountVectorizer()
x = count.fit_transform(corpus)

In [25]:
x

<7x23 sparse matrix of type '<class 'numpy.int64'>'
	with 36 stored elements in Compressed Sparse Row format>

In [26]:
count.get_feature_names()

['are',
 'bad',
 'birthday',
 'day',
 'good',
 'happening',
 'having',
 'hello',
 'how',
 'im',
 'is',
 'its',
 'my',
 'neither',
 'nothing',
 'or',
 'really',
 'so',
 'special',
 'super',
 'there',
 'today',
 'you']

In [27]:
print( x.toarray())

[[1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 1 0 0 0 0 0 0 0 2 1 0 0 0 1 1 1 0 0 0 0]
 [0 1 0 2 1 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0]
 [0 1 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0]
 [0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0]]


In [28]:
df2 = pd.DataFrame({'text' : corpus})

In [29]:
df2

text
0                            hello how are you
1                          today is a good day
2  its my birthday so its a really special day
3     today is neither a good day or a bad day
4                          im having a bad day
5      there s nothing special happening today
6                    today is a super good day

In [33]:
df['positive1'] = df2.text.str.count('good')
df['positive2']= df2.text.str.count('special')
df['negative'] = df2.text.str.count('bad')
df['TotScore'] = df2.positive1 + df.positive2 - df.negative


In [34]:
df

Day of Week                                     comments  positive1  \
0      Monday                            hello how are you          0   
1     Tuesday                          today is a good day          1   
2   Wednesday  its my birthday so its a really special day          0   
3    Thursday     today is neither a good day or a bad day          1   
4      Friday                          im having a bad day          0   
5    Saturday      there s nothing special happening today          0   
6      Sunday                    today is a super good day          1   

   positive2  negative  TotScore  
0          0         0         0  
1          0         0         1  
2          1         0         1  
3          0         1         0  
4          0         1        -1  
5          1         0         1  
6          0         0         1